
name: Run Notebooks

on:
  push:
  pull_request:

jobs:
  run-notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install jupyter nbconvert

      - name: Execute Project 3 notebook
        run: |
          jupyter nbconvert --to notebook --inplace --execute project3-eda/*.ipynb --ExecutePreprocessor.timeout=1800

      - name: Execute Project 4 notebook
        run: |
          jupyter nbconvert --to notebook --inplace --execute project4-ml/*.ipynb --ExecutePreprocessor.timeout=1800
